config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  #
  resources :products, only: [:show, :index]
  get "carts", to: "carts#show"

  resources :order_products, only: [:create]
  post "remove_from_cart/:product_id", to: "order_products#remove_from_cart", as: :remove_from_cart
  post "delete_from_cart/:product_id", to: "order_products#delete_from_cart", as: :delete_from_cart
  resources :charges

  resources :playlists, only: [:index, :create, :new]
  resources :orders, only: [:create, :show]


  get "dashboard", to: "dashboards#overview"

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :supplier, optional: true
  has_many :orders

  validates :street, :city, :zip, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :order_products
  before_save :set_subtotal

  def subtotal
    order_products.collect {|order_product| order_product.valid? ? (order_product.unit_price*order_product.quantity) : 0}.sum
  end

  private
    def set_subtotal
      self[:subtotal] = subtotal
    end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :product
  belongs_to :supplier
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :address
  has_many :order_products
  has_many :products, through: :order_products


end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total_price

  def price_per_unit
    if persisted?
      self[price_per_unit]
    else
      product.price
    end
  end

  def tot_price
    price_per_unit * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = price_per_unit
  end

  def set_total_price
    self[:total_price] = quantity * set_unit_price
  end
end

app/models/playlist.rb
class Playlist < ApplicationRecord
 has_many :playlist_products
 has_many :products, through: :playlist_products
end

app/models/playlist_product.rb
class PlaylistProduct < ApplicationRecord
  belongs_to :playlist
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :subcategory, optional: true
  belongs_to :category
  belongs_to :supplier
  has_many :inventories
  has_many :order_products
  has_many :orders, through: :order_products
  has_many :playlist_products
  has_many :playlists, through: :playlist_products
  validates :barcode, :name, presence: true


end

app/models/shopping_preference.rb
class ShoppingPreference < ApplicationRecord
  has_many :user_preferences

end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  has_many :products
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :address, optional: true
  has_many :products
  has_many :inventories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_preferences
  has_many :shopping_preferences, through: :user_preferences
  belongs_to :address
  accepts_nested_attributes_for :address
end

app/models/user_preference.rb
class UserPreference < ApplicationRecord
  belongs_to :user
  belongs_to :shopping_preference

  validates :user, :shopping_preference, :order, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @order_products = []
    @current_cart.each do |product_id, quantity|
      order_product = OrderProduct.new(
        product_id: product_id,
        quantity: quantity,
        unit_price: Product.find(product_id).price
        )
      @order_products << order_product
    end

    if @order_products.empty?
      flash[:notice] = 'Empty Cart, redirecting you to product browsing page...'
      sleep(5)
      redirect_to products_path
    end
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @order_products = []
    @current_cart.each do |product_id, quantity|
      order_product = OrderProduct.new(
        product_id: product_id,
        quantity: quantity,
        unit_price: Product.find(product_id).price
        )
      @order_products << order_product
    end
  end

  def create
   @cart_amount = @current_cart.inject(0) do |sum, (key, quantity)|
      @product = Product.find(key)
      sum += @product.price * quantity
    end

   @order = Order.new(
     status: "Payment not accepted",
     user_id: current_user.id,
     deliver_date: Date.today + 1,
     address_id: current_user.address.id,
     total: @cart_amount
    )
   @order.save!

   @current_cart.each do |product_id, quantity|
      order_product = OrderProduct.new(
        product_id: product_id,
        quantity: quantity,
        unit_price: Product.find(product_id).price,
        order_id: @order.id
       )
      order_product.save!
    end

    # Amount in cents
    @amount = @cart_amount * 100

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount.to_i,
      description: 'Rails Stripe customer',
      currency: 'chf',
    })


    @order.status = "Pending"
    session.delete(:cart)
    redirect_to dashboard_path, notice: 'Payment approved!'

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path

  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Oishi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="">
  <%# orange triangle %>
  <section class="rectangle paper"></section>

<%# illustration %>
  <div class="illustration justify-content-lg-end">
    <div id="leeks">
      <img src="images/leeks.png" alt="">
    </div>
    <div id="cherries"></div>
    <div id="cumcumber"></div>
    <div id="watermelon"></div>
    <div id="beacon"></div>
    <div id="fish"></div>
    <%= image_tag "leeks.png" %>

  </div>

  <div class="title">
    <div class="d-flex align-items-start flex-column">
      <h3 class="catch-phrase">cheaper, greener, healthier.</h3>
      <h1>oishi.</h1>
      <div><%= link_to "Browse", products_path, class: "btn btn-info btn-lg" %></div>
    </div>
  </div>

  <%# <div class="container-content-pages m-8">
    <h2 class="text-center">Monitor your consumption habits while doing your groceries online</h2>
    <div class="container-content-purpose d-flex mt-4">
      <div class="quote w-25">
        <p>
          "By 2030, ensure that people everywhere have the relevant information and
            awareness for sustainable development and lifestyles in harmony with
            nature." - United Nations Sustainable Development Goal n°12
        </p>
      </div>

      <div class="oishi-list">
        <ul>
          <li>
            <h3><strong>Grocery shopping facilitator</strong></h3>
            <p>Oishi provides you data to help you in your grocery shopping journey with simple
            indicators to help you make the right decisions</p>
          </li>
          <li>
            <h3><strong>Suggestions</strong></h3>
            <p>For every product, Oishi displays suggestests you eco-friendlier alternatives.</p>

          </li>
          <li>
            <h3><strong>Dashboard</strong></h3>
            <p>Monitor your consumption and see your improvements. We truly believe that the right data will allow us
            to improve our consumption habbits.</p>
          </li>
        </ul>
      </div>
    </div>
  </div> %>

</div>

app/views/shared/_cart.html.erb
<div class="container shopping">
  <div class="row">
  <i class="fas fa-cart-arrow-down fa-lg shop-logo" ></i>
    <%= link_to " #{@current_cart.values.reduce(:+)}  items", carts_path, class: "nav-link" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-4 d-flex justify-content-around" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-4 d-flex justify-content-around" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <%= link_to "oishi.", root_path, class: "nav-logo" %>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if session[:cart].present? %>
        <li class="nav-item active " id ="cart">
          <%= render 'shared/cart' %>
        </li>
      <% end %>
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Products", products_path, class: "btn btn-primary mr-2" %>
        </li>
        <li class="nav-item dropdown">


          <%= image_tag "https://kitt.lewagon.com/placeholder/users/emmanuelferreira", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>


          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
          <ul class="navbar-nav">
            <li class="nav-item active d-flex">
              <%= link_to "Sign up", new_user_registration_path, class: "btn btn-info btn-lg mr-2" %>
            </li>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "btn btn-primary btn-lg ml-2" %>
            </li>
          </ul>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_popup.html.erb
<div class="modal fade" id="modal-<%= product.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title" id="exampleModalLabel"><%= product.name.capitalize %></h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-4">
              <h5><%=product.category.name %></h5>
              <div class="show-emotes">
                <i class="fas fa-leaf"></i>
                <i class="fas fa-heartbeat"></i>
                <i class="fas fa-dollar-sign"></i>
              </div>
              <img src="<%= product.image%>" style="height:300px;" alt="" class="img-show">
            </div>
            <div class="col-md-8 ml-auto">
              <div class="row basket-selection">
                <div class="col-4">
                  <div class="quantity-show">
                    <p>Quantity</p>
                    <div class="min-max-q-show">
                      <input type="number" value="0" id="input"/>
                    </div>
                  </div>
                </div>
                <div class="col-4">
                  <div class="price-show">
                    <p>Price</p>
                    <h4><%=product.price  %></h4>
                  </div>
                </div>
                <div class="col-4">
                  <div class="btn-basket-show">
                    <%= link_to "ADD TO BASKET", "#", class: "btn btn-flat btn-basket" %>
                  </div>
                </div>
              </div>

              <div class="row">

                <div class="col-4">
                  <div class="list-group" id="list-tab" role="tablist">
                    <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Description</a>
                    <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">Nutritional value</a>
                    <a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages">Eco Impact</a>
                    <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">About</a>
                  </div>
                </div>
                <div class="col-8">
                  <div class="tab-content" id="nav-tabContent">
                    <div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">Irure enim occaecat labore sit qui aliquip reprehenderit amet velit. Deserunt ullamco ex elit nostrud ut dolore nisi officia magna sit occaecat laboris sunt dolor.</div>
                    <div class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">Nisi eu minim cillum occaecat aute est cupidatat aliqua labore aute occaecat ea aliquip sunt amet.</div>
                    <div class="tab-pane fade" id="list-messages" role="tabpanel" aria-labelledby="list-messages-list">Aute mollit dolor ut exercitation irure commodo non amet consectetur quis amet culpa.</div>
                    <div class="tab-pane fade" id="list-settings" role="tabpanel" aria-labelledby="list-settings-list">Quis ullamco nisi amet qui aute irure eu. Magna labore dolor quis ex labore id nostrud deserunt dolor eiusmod eu pariatur culpa mollit in irure.</div>
                  </div>
                </div>

              </div>
            </div>
          </div>

          <div class="row suggestion-title">
            <h1>Suggestions</h1>
          </div>
          <div class="row">
            <div class="col img-suggestions">
              <img src="https://images.unsplash.com/photo-1584306670957-acf935f5033c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=666&q=80" style="height:300px;" alt="" class="img-show">
            </div>
            <div class="col img-suggestions">
              <img src="https://images.unsplash.com/photo-1584306670957-acf935f5033c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=666&q=80" style="height:300px;" alt="" class="img-show">
            </div>
            <div class="col img-suggestions">
              <img src="https://images.unsplash.com/photo-1584306670957-acf935f5033c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=666&q=80" style="height:300px;" alt="" class="img-show">
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_tabs.html.erb
<div class="tabs-container">
  <ul class="list-inline tabs-underlined paper scrollmenu">
    <% Category.all.each do |category| %>
      <li class="scroll">
        <%= form_tag products_path, method: :get, :class => 'form-inline' do %>
          <%= hidden_field_tag :query, category.name %>
          <%= submit_tag "#{category.name == "Plant-based-foods-and-beverages" ? "PLANT BASED" :category.name.upcase }", class: "btn btn-flat btn-all d-flex justify-content-around w-75"  %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>