config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  #
  resources :products, only: [:show, :index]
  get "carts", to: "carts#show"

  resources :order_products, only: [:create]
  post "remove_from_cart/:product_id", to: "order_products#remove_from_cart", as: :remove_from_cart
  post "delete_from_cart/:product_id", to: "order_products#delete_from_cart", as: :delete_from_cart
  resources :charges

  resources :playlists, only: [:index, :create, :new]
  resources :orders, only: [:create, :show]


  get "dashboard", to: "dashboards#overview"

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :supplier, optional: true
  has_many :orders

  validates :street, :city, :zip, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :order_products
  before_save :set_subtotal

  def subtotal
    order_products.collect {|order_product| order_product.valid? ? (order_product.unit_price*order_product.quantity) : 0}.sum
  end

  private
    def set_subtotal
      self[:subtotal] = subtotal
    end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :product
  belongs_to :supplier
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :address
  has_many :order_products
  has_many :products, through: :order_products


end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total_price

  def price_per_unit
    if persisted?
      self[price_per_unit]
    else
      product.price
    end
  end

  def tot_price
    price_per_unit * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = price_per_unit
  end

  def set_total_price
    self[:total_price] = quantity * set_unit_price
  end
end

app/models/playlist.rb
class Playlist < ApplicationRecord
 has_many :playlist_products
 has_many :products, through: :playlist_products
end

app/models/playlist_product.rb
class PlaylistProduct < ApplicationRecord
  belongs_to :playlist
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :subcategory, optional: true
  belongs_to :category
  belongs_to :supplier
  has_many :inventories
  has_many :order_products
  has_many :orders, through: :order_products
  has_many :playlist_products
  has_many :playlists, through: :playlist_products
  validates :barcode, :name, presence: true


end

app/models/shopping_preference.rb
class ShoppingPreference < ApplicationRecord
  has_many :user_preferences

end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  has_many :products
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :address, optional: true
  has_many :products
  has_many :inventories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_preferences
  has_many :shopping_preferences, through: :user_preferences
  belongs_to :address
  accepts_nested_attributes_for :address
end

app/models/user_preference.rb
class UserPreference < ApplicationRecord
  belongs_to :user
  belongs_to :shopping_preference

  validates :user, :shopping_preference, :order, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @order_products = []
    @current_cart.each do |product_id, quantity|
      order_product = OrderProduct.new(
        product_id: product_id,
        quantity: quantity,
        unit_price: Product.find(product_id).price
        )
      @order_products << order_product
    end

    if @order_products.empty?
      flash[:notice] = 'Empty Cart, redirecting you to product browsing page...'
      sleep(5)
      redirect_to products_path
    end
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @order_products = []
    @current_cart.each do |product_id, quantity|
      order_product = OrderProduct.new(
        product_id: product_id,
        quantity: quantity,
        unit_price: Product.find(product_id).price
        )
      @order_products << order_product
    end
  end

  def create
   @cart_amount = @current_cart.inject(0) do |sum, (key, quantity)|
      @product = Product.find(key)
      sum += @product.price * quantity
    end

   @order = Order.new(
     status: "Payment not accepted",
     user_id: current_user.id,
     deliver_date: Date.today + 1,
     address_id: current_user.address.id,
     total: @cart_amount
    )
   @order.save!

   @current_cart.each do |product_id, quantity|
      order_product = OrderProduct.new(
        product_id: product_id,
        quantity: quantity,
        unit_price: Product.find(product_id).price,
        order_id: @order.id
       )
      order_product.save!
    end

    # Amount in cents
    @amount = @cart_amount * 100

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount.to_i,
      description: 'Rails Stripe customer',
      currency: 'chf',
    })


    @order.status = "Pending"
    session.delete(:cart)
    redirect_to dashboard_path, notice: 'Payment approved!'

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path

  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @playlists = Playlist.all
    @eco_scores = Playlist.find_by(name: "eco_score")
    @nutri_scores = Playlist.find_by(name: "nutri_score")
    @prices = Playlist.find_by(name: "price_score")

    @nutri_products = Product.joins(:category, :comments)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
     if params[:query].present? && params[:sort_eco].present?
      @products = Product.where(category_id: Category.find_by(name: params[:query]).id).sort_by(&:eco_score)
      @order_product = OrderProduct.new
    elsif params[:query].present? && params[:sort_nutri].present?
      @products = Product.where(category_id: Category.find_by(name: params[:query]).id).sort_by(&:nutri_score)
      @order_product = OrderProduct.new
    elsif params[:query].present? && params[:sort_price].present?
      @products = Product.where(category_id: Category.find_by(name: params[:query]).id).sort_by(&:price)
      @order_product = OrderProduct.new
    elsif params[:query].present?
      @products = Product.where(category_id: Category.find_by(name: params[:query]).id).sort_by(&:eco_score)
      @suppliers = Supplier.all
      @order_product = OrderProduct.new
    elsif params[:sort_eco].present?
      @products = Product.all.sort_by(&:eco_score)
      @suppliers = Supplier.all
      @order_product = OrderProduct.new
    elsif params[:sort_nutri].present?
      @products = Product.all.sort_by(&:nutri_score)
      @suppliers = Supplier.all
      @order_product = OrderProduct.new
    elsif params[:sort_price].present?
      @products = Product.all.sort_by(&:price)
      @suppliers = Supplier.all
      @order_product = OrderProduct.new
    else
      @products = Product.includes(:category).sort_by(&:eco_score)
      @suppliers = Supplier.all
      @order_product = OrderProduct.new
    end
  end

  def show
    @product = Product.includes(:category).find(params[:id])
    @order_product = OrderProduct.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/carts/show.html.erb
<section class="rectangle paper"></section>
<section class="rectangle_bottom paper"></section>

<div class="cart-title">
  <h2>Cart</h2>
</div>

<div class="container py-6 d-flex justify-content-center">
  <div class="card-cart container-products col-10 cart-item">
    <% @order_products.each do |item| %>
      <div class="card-product-cart" data-toggle="modal" data-target="#modal-<%= item.product.id %>">
        <%= image_tag item.product.image, class: "", style: "width: 200px; height: 300px;"  %>
        <div class="card-product-infos flex-grow-1">
          <div class="d-flex justify-content-between ">
            <h2><%= item.product.name.capitalize %></h2>
            <h2><%= item.product.price.round(2)%><%= item.product.currency.upcase %></h2>
          </div>
          <h3> <%= item.product.category.name %> </h3>
          <div class="d-flex justify-content-around">
            <% if item.product.eco_score == "A" || item.product.eco_score == "B"%>
              <i class="fas fa-globe-americas fa-2x pl-3" style="color: #4CA90C;"></i>
            <%elsif  item.product.eco_score == "C" || item.product.eco_score == "D"%>
              <i class="fas fa-globe-americas fa-2x pl-3" style="color: #FFC400;"></i>
            <% else %>
              <i class="fas fa-globe-americas fa-2x pl-3" style="color: #EB5757;"></i>
            <% end %>
            <% if item.product.nutri_score == "A" || item.product.nutri_score == "B"%>
              <i class="fas fa-heartbeat fa-2x pl-3" style="color: #4CA90C;"></i>
            <%elsif  item.product.nutri_score == "C" || item.product.nutri_score == "D"%>
              <i class="fas fa-heartbeat fa-2x pl-3" style="color: #FFC400;"></i>
            <% else %>
              <i class="fas fa-heartbeat fa-2x pl-3" style="color: #EB5757;"></i>
            <% end %>
            <% if item.product.price < 0.8 * ((Product.where(category_id: item.product.category.id).pluck(:price).inject { |sum, el| sum + el }.to_f)/Product.where(category_id: item.product.category.id).size) %>
              <i class="fas fa-money-bill-wave fa-2x pl-3" style="color: #4CA90C;"></i>
            <% elsif item.product.price >= 0.8 * ((Product.where(category_id: item.product.category.id).pluck(:price).inject { |sum, el| sum + el }.to_f)/Product.where(category_id: item.product.category.id).size) && item.product.price <= 1.2 * ((Product.where(category_id: item.product.category.id).pluck(:price).inject { |sum, el| sum + el }.to_f)/Product.where(category_id: item.product.category.id).size) %>
              <i class="fas fa-money-bill-wave fa-2x pl-3" style="color: #FFC400;"></i>
            <% else %>
              <i class="fas fa-money-bill-wave fa-2x pl-3" style="color: #EB5757;"></i>
            <% end %>
          </div>

          <div class="d-flex justify-content-end m-3">
            <div class="">
              <div>
                <%= form_for(item, url: remove_from_cart_path(item.product.id), remote: true) do |f| %>
                  <%= f.hidden_field :product_id, value: item.product.id, class: "form-control" %>
                    <%= button_tag type: 'Update', class: "button-update-cart", id: "update-button" do %>
                      <i class="fa fa-sync fa-lg" aria-hidden="true"></i>
                    <% end %>
                  <%= link_to delete_from_cart_path(item.product.id), method: :post, remote: true, class: "button-delete-cart" do%>
                    <i class="fa fa-trash fa-lg"></i>
                  <% end %>
                  <%= f.text_field :quantity, value: item.quantity, min: 1, class: 'form-control quantity-cart' %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %> 

    <% if @order_products.present? %>
      <label class="amount d-flex justify-content-center">
        <span><STRONG>Total Amount:</STRONG>
          <%= @current_cart.inject(0) do |sum, (key, quantity)|
            @product = Product.find(key)
            sum += @product.price * quantity
          end.round(2)  %>
            CHF
        </span>
      </label>
      <div class="container-link-to-strip py-3 d-flex justify-content-center">
        <%= link_to "Process Order", new_charge_path, class: "btn btn-info btn-lg " %>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<div class="rectangle paper"></div>
<section class="rectangle_bottom paper"></section>


<div class="container py-6">
  <div class="container-products col-lg-12 cart-item card-product-order">
    <h1> Order N° <%= @order.id  %> </h1>
    <p> <em>Delivered on <%= @order.deliver_date %></em></p>
    <% @order_products.each do |item| %>
      <div class="card-product" data-toggle="modal" data-target="#modal-<%= item.product.id %>">
        <%= image_tag item.product.image %>
        <div class="card-product-infos flex-grow-1">
          <div class="d-flex justify-content-between ">
            <h2><%= item.product.name.capitalize %></h2>
            <h2><%= item.product.price%><%= item.product.currency.upcase %></h2>
          </div>
          <h3><%= item.product.category.name %></h3>
          <div class="d-flex justify-content-around badges ">
            <% if item.product.eco_score == "A" || item.product.eco_score == "B"%>
              <i class="fas fa-globe-americas fa-2x" style="color: #4CA90C;"></i>
            <%elsif  item.product.eco_score == "C" || item.product.eco_score == "D"%>
              <i class="fas fa-globe-americas fa-2x" style="color: #FFC400;"></i>
            <% else %>
              <i class="fas fa-globe-americas fa-2x" style="color: #EB5757;"></i>
            <% end %>
            <% if item.product.nutri_score == "A" || item.product.nutri_score == "B"%>
              <i class="fas fa-heartbeat fa-2x pl-3" style="color: #4CA90C;"></i>
            <%elsif  item.product.nutri_score == "C" || item.product.nutri_score == "D"%>
              <i class="fas fa-heartbeat fa-2x pl-3" style="color: #FFC400;"></i>
            <% else %>
              <i class="fas fa-heartbeat fa-2x pl-3" style="color: #EB5757;"></i>
            <% end %>

            <% if item.product.price < 0.8 * ((Product.where(category_id: item.product.category.id).pluck(:price).inject { |sum, el| sum + el }.to_f)/Product.where(category_id: item.product.category.id).size) %>
              <i class="fas fa-money-bill-wave fa-2x pl-3" style="color: #4CA90C;"></i>
            <% elsif item.product.price >= 0.8 * ((Product.where(category_id: item.product.category.id).pluck(:price).inject { |sum, el| sum + el }.to_f)/Product.where(category_id: item.product.category.id).size) && item.product.price <= 1.2 * ((Product.where(category_id: item.product.category.id).pluck(:price).inject { |sum, el| sum + el }.to_f)/Product.where(category_id: item.product.category.id).size) %>
              <i class="fas fa-money-bill-wave fa-2x pl-3" style="color: #FFC400;"></i>
            <% else %>
              <i class="fas fa-money-bill-wave fa-2x pl-3" style="color: #EB5757;"></i>
            <% end %>
          </div>
          <div class="d-flex justify-content-between">
            <p class="flex-grow overflow-auto"><%= item.product.description%></p>
          </div>
        </div>
      </div>
      <%# <%= render 'products/popup', product: item.product%>
    <% end %>
  </div>
</div>

app/views/products/_popup.html.erb
<div class="modal fade" id="modal-<%= product.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="popup-product-details d-flex justify-content-between">
        <div class="modal-left-section">
          <div class="modal-header-details">
            <%= image_tag product.image, class: "img-show mb-4" %>
            <div class="d-flex justify-content-between mb-2" pt-3>
              <% if product.eco_score == "A" || product.eco_score == "B"%>
                <i class="fas fa-globe-americas fa-2x" style="color: #4CA90C;"></i>
              <%elsif  product.eco_score == "C" || product.eco_score == "D"%>
                <i class="fas fa-globe-americas fa-2x" style="color: #FFC400;"></i>
              <% else %>
                <i class="fas fa-globe-americas fa-2x" style="color: #EB5757;"></i>
              <% end %>
              <% if product.nutri_score == "A" || product.nutri_score == "B"%>
                <i class="fas fa-heartbeat fa-2x pl-3" style="color: #4CA90C;"></i>
              <%elsif  product.nutri_score == "C" || product.nutri_score == "D"%>
                <i class="fas fa-heartbeat fa-2x pl-3" style="color: #FFC400;"></i>
              <% else %>
                <i class="fas fa-heartbeat fa-2x pl-3" style="color: #EB5757;"></i>
              <% end %>
              <% if product.price < 0.8 * ((Product.where(category_id: product.category.id).pluck(:price).inject { |sum, el| sum + el }.to_f)/Product.where(category_id: product.category.id).size) %>
                <i class="fas fa-money-bill-wave fa-2x pl-3" style="color: #4CA90C;"></i>
              <% elsif product.price >= 0.8 * ((Product.where(category_id: product.category.id).pluck(:price).inject { |sum, el| sum + el }.to_f)/Product.where(category_id: product.category.id).size) && product.price <= 1.2 * ((Product.where(category_id: product.category.id).pluck(:price).inject { |sum, el| sum + el }.to_f)/Product.where(category_id: product.category.id).size) %>
                <i class="fas fa-money-bill-wave fa-2x pl-3" style="color: #FFC400;"></i>
              <% else %>
                <i class="fas fa-money-bill-wave fa-2x pl-3" style="color: #EB5757;"></i>
              <% end %>
            </div>
          </div>
          <div class="popup-product-details pt-3">
            <div class="popup-product-details-section d-flex justify-content-between">
              <div class= "popup-product-details-price">
                <h3>Price</h3>
                <p> <strong> <%= product.price %> CHF </strong>  </p>
              </div>
              <% if @order_product.present? %>
                <div class="quantity-show">
                  <h3>Quantity</h3>
                  <%= form_for @order_product, class: "form-group add-button", remote: true, redirect_to: products_path do |f| %>
                    <%= f.hidden_field :product_id, value: product.id%>
                    <%= f.text_field :quantity, value: 1, min: 1, size: 2 %>
                </div>
            </div>
                    <%= f.submit "Add to basket", size: 10, class:"btn btn-info m-3" %>
                  <% end %>
            <% end %>
          </div>
        </div>
        <div class="modal-right-section flex-grow-1 pl-4">
          <button type="button" class="close" data-dismiss="modal" aria-label="close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h2 class="modal-title ml-3" id="exampleModalLabel"> <%= product.name.capitalize %></h2>
          <h3 class="ml-3"><%=product.category.name %></h3>
          <div class="modal-body d-flex flex-column justify-content-between">
            <h2>Description</h2>
            <p><%= product.description.capitalize if product.description.present? %> </p>
            <h2>Data</h2>
            <div class="product-data">
              <h3>Ecoscore data</h3>
              <div class="grid-container-ecoscore">
                <p><strong>Eco-score:</strong> <%= product.eco_score %></p>
                <p><strong>Origin:</strong> <%= product["origin"] %> </p>
              </div>
              <h3>Nutriscore data <em>(/100g)</em></h3>
              <div class="grid-container-nutriscore">
                <p><strong>Nutri-score:</strong> <%= product.nutri_score %></p>
                <p><strong>Energie:</strong> <%= product["nutriments"]["energy-kcal_100g"] %> Kcal </p>
                <p><strong>Carbohydrates:</strong> <%= product["nutriments"]["carbohydrates_100g"] %></p>
                <p><strong>Proteins:</strong> <%= product["nutriments"]["proteins_100g"] %></p>
                <p><strong>Fat:</strong> <%= product["nutriments"]["fat_100g"] %></p>
                <p><strong>Saturated fat:</strong> <%= product["nutriments"]["saturated-fat_100g"] %></p>
                <p><strong>Salt:</strong> <%= product["nutriments"]["salt_100g"] %> </p>
                <p><strong>Sugars:</strong> <%= product["nutriments"]["sugars_100g"] %> </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="suggestion">
        <% if product.eco_score == "A" || product.eco_score == "B" %>
            <h4 class="suggestion-title">You rock<i class="fas fa-grin-alt" style="color:green; margin-left: 10px;"></i></h4>
            <div class="row suggestions-list d-flex justify-content-around">
              <p class="thanks"> By purchasing this product you are doing a great gesture for the future generations! Cheers from Greta... she is already in love with you <i class="fas fa-fw fa-heart text-center" style="color: red;"></i></p>
            </div>
        <% else %>
            <h4 class="suggestion-title">Eco-friendly Suggestions</h4>
            <div class="row suggestions-list d-flex justify-content-around ">
              <% Product.where(category: product.category).order(eco_score: :asc).take(3).each do |product_suggestion| %>
                <div class="img-suggestions">
                  <%= image_tag product_suggestion.image %>
                  <%= link_to "", product_path(product_suggestion)  %>
                </div>
              <% end %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
 <div class="index-banner"></div>

<div class="container-show-product w-70" >
  <div class="popup-product-details d-flex justify-content-between p-4">
    <div class="show-left-section">
      <div class="show-header-details">
        <%= image_tag @product.image, class: "img-show mb-4" %>
        <div class="d-flex justify-content-between" pt-3>
          <% if @product.eco_score == "A" || @product.eco_score == "B"%>
            <i class="fas fa-globe-americas fa-2x" style="color: #4CA90C;"></i>
          <%elsif  @product.eco_score == "C" || @product.eco_score == "D"%>
            <i class="fas fa-globe-americas fa-2x" style="color: #FFC400;"></i>
          <% else %>
            <i class="fas fa-globe-americas fa-2x" style="color: #EB5757;"></i>
          <% end %>
          <% if @product.nutri_score == "A" || @product.nutri_score == "B"%>
            <i class="fas fa-heartbeat fa-2x pl-3" style="color: #4CA90C;"></i>
          <%elsif  @product.nutri_score == "C" || @product.nutri_score == "D"%>
            <i class="fas fa-heartbeat fa-2x pl-3" style="color: #FFC400;"></i>
          <% else %>
            <i class="fas fa-heartbeat fa-2x pl-3" style="color: #EB5757;"></i>
          <% end %>
          <% if @product.price < 0.8 * ((Product.where(category_id: @product.category.id).pluck(:price).inject { |sum, el| sum + el }.to_f)/Product.where(category_id: @product.category.id).size) %>
            <i class="fas fa-money-bill-wave fa-2x pl-3" style="color: #4CA90C;"></i>
          <% elsif @product.price >= 0.8 * ((Product.where(category_id: @product.category.id).pluck(:price).inject { |sum, el| sum + el }.to_f)/Product.where(category_id: @product.category.id).size) && @product.price <= 1.2 * ((Product.where(category_id: @product.category.id).pluck(:price).inject { |sum, el| sum + el }.to_f)/Product.where(category_id: @product.category.id).size) %>
            <i class="fas fa-money-bill-wave fa-2x pl-3" style="color: #FFC400;"></i>
          <% else %>
            <i class="fas fa-money-bill-wave fa-2x pl-3" style="color: #EB5757;"></i>
          <% end %>
        </div>
      </div>
      <div class="popup-product-details pt-3">
        <div class="popup-product-details-section d-flex justify-content-between">
          <div class= "popup-product-details-price">
            <h4 class="show-price">Price</h4>
            <p> <strong> <%= @product.price %> CHF </strong>  </p>
          </div>
          <% if @order_product.present? %>
            <div class="quantity-show">
              <h4 class="show-price">Quantity</h4>
              <%= form_for @order_product, class: "form-group add-button", redirect_to: products_path do |f| %>
                <%= f.hidden_field :product_id, value: @product.id%>
                <%= f.text_field :quantity, value: 1, min: 1, size: 2 %>
            </div>
        </div>
                <%= f.submit "Add to basket", size: 10, class:"btn btn-info m-3" %>
              <% end %>
        <% end %>
      </div>
    </div>
    <div class="show-right-section flex-grow-1 pl-4">
      <h1 class="show-title" id="exampleshowLabel"> <%= @product.name.capitalize %></h1>
      <h3 class="show-category mb-4"><%=@product.category.name %></h3>
      <div class="show-body d-flex flex-column justify-content-between">
        <h3>Description</h3>
        <p><%= @product.description.capitalize if @product.description.present? %> </p>
        <h3>Data</h3>
        <div class="product-data">
          <h4>Ecoscore data</h4>
          <div class="grid-container-ecoscore">
            <p><strong>Eco-score:</strong> <%= @product.eco_score %></p>
            <p><strong>Origin:</strong> <%= @product["origin"] %> </p>
          </div>
          <h4 class="d-flex justify-content-start">Nutriscore data <em>(/100g)</em></h4>
          <div class="grid-container-nutriscore">
            <p><strong>Nutri-score:</strong> <%= @product.nutri_score %></p>
            <p><strong>Energie:</strong> <%= @product["nutriments"]["energy-kcal_100g"] %> Kcal </p>
            <p><strong>Proteins:</strong> <%= @product["nutriments"]["proteins_100g"] %></p>
            <p><strong>Fat:</strong> <%= @product["nutriments"]["fat_100g"] %></p>
            <p><strong>Carbohydrates:</strong> <%= @product["nutriments"]["carbohydrates_100g"] %></p>
            <p><strong>Saturated fat:</strong> <%= @product["nutriments"]["saturated-fat_100g"] %></p>
            <p><strong>Salt:</strong> <%= @product["nutriments"]["salt_100g"] %> </p>
            <p><strong>Sugars:</strong> <%= @product["nutriments"]["sugars_100g"] %> </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="suggestion">
    <% if @product.eco_score == "A" || @product.eco_score == "B" %>
        <h4 class="suggestion-title">You rock<i class="fas fa-grin-alt" style="color:green; margin-left: 10px;"></i></h4>
        <div class="row suggestions-list d-flex justify-content-around">
          <p> By purchasing this product you are doing a great gesture for the future generations! Cheers from Greta... she is already in love with you <i class="fas fa-fw fa-heart" style="color: red;"></i></p>
        </div>
    <% else %>
        <h4 class="suggestion-title">Eco-friendly Suggestions</h4>
        <div class="row suggestions-list d-flex justify-content-around ">
          <% Product.where(category: @product.category).order(eco_score: :asc).take(3).each do |product_suggestion| %>
            <div class="img-suggestions mb-4">
              <%= image_tag product_suggestion.image %>
              <%= link_to "", product_path(product_suggestion)  %>
            </div>
          <% end %>
        </div>
    <% end %>
  </div>
</div>