config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  #
  resources :products, only: [:show, :index]
  get "carts", to: "carts#show"

  resources :order_products, only: [:create]
  post "remove_from_cart/:product_id", to: "order_products#remove_from_cart", as: :remove_from_cart
  post "delete_from_cart/:product_id", to: "order_products#delete_from_cart", as: :delete_from_cart
  resources :charges

  resources :playlists, only: [:index, :create, :new]
  resources :orders, only: [:create, :show]


  get "dashboard", to: "dashboards#overview"

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :supplier, optional: true
  has_many :orders

  validates :street, :city, :zip, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :order_products
  before_save :set_subtotal

  def subtotal
    order_products.collect {|order_product| order_product.valid? ? (order_product.unit_price*order_product.quantity) : 0}.sum
  end

  private
    def set_subtotal
      self[:subtotal] = subtotal
    end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :product
  belongs_to :supplier
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :address
  has_many :order_products
  has_many :products, through: :order_products


end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
  before_save :set_unit_price
  before_save :set_total_price

  def price_per_unit
    if persisted?
      self[price_per_unit]
    else
      product.price
    end
  end

  def tot_price
    price_per_unit * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = price_per_unit
  end

  def set_total_price
    self[:total_price] = quantity * set_unit_price
  end
end

app/models/playlist.rb
class Playlist < ApplicationRecord
 has_many :playlist_products
 has_many :products, through: :playlist_products
end

app/models/playlist_product.rb
class PlaylistProduct < ApplicationRecord
  belongs_to :playlist
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :subcategory, optional: true
  belongs_to :category
  belongs_to :supplier
  has_many :inventories
  has_many :order_products
  has_many :orders, through: :order_products
  has_many :playlist_products
  has_many :playlists, through: :playlist_products
  validates :barcode, :name, presence: true


end

app/models/shopping_preference.rb
class ShoppingPreference < ApplicationRecord
  has_many :user_preferences

end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  has_many :products
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  belongs_to :address, optional: true
  has_many :products
  has_many :inventories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_preferences
  has_many :shopping_preferences, through: :user_preferences
  belongs_to :address
  accepts_nested_attributes_for :address
end

app/models/user_preference.rb
class UserPreference < ApplicationRecord
  belongs_to :user
  belongs_to :shopping_preference

  validates :user, :shopping_preference, :order, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authenticate_user!

  def show
    @order_products = []
    @current_cart.each do |product_id, quantity|
      order_product = OrderProduct.new(
        product_id: product_id,
        quantity: quantity,
        unit_price: Product.find(product_id).price
        )
      @order_products << order_product
    end

    if @order_products.empty?
      flash[:notice] = 'Empty Cart, redirecting you to product browsing page...'
      sleep(5)
      redirect_to products_path
    end
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @order_products = []
    @current_cart.each do |product_id, quantity|
      order_product = OrderProduct.new(
        product_id: product_id,
        quantity: quantity,
        unit_price: Product.find(product_id).price
        )
      @order_products << order_product
    end
  end

  def create
   @cart_amount = @current_cart.inject(0) do |sum, (key, quantity)|
      @product = Product.find(key)
      sum += @product.price * quantity
    end

   @order = Order.new(
     status: "Payment not accepted",
     user_id: current_user.id,
     deliver_date: Date.today + 1,
     address_id: current_user.address.id,
     total: @cart_amount
    )
   @order.save!

   @current_cart.each do |product_id, quantity|
      order_product = OrderProduct.new(
        product_id: product_id,
        quantity: quantity,
        unit_price: Product.find(product_id).price,
        order_id: @order.id
       )
      order_product.save!
    end

    # Amount in cents
    @amount = @cart_amount * 100

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount.to_i,
      description: 'Rails Stripe customer',
      currency: 'chf',
    })


    @order.status = "Pending"
    session.delete(:cart)
    redirect_to dashboard_path, notice: 'Payment approved!'

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path

  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController


  def overview
    # @last_order = Order.where(user_id: current_user.id).last
    # @order_products = OrderProduct.where(order_id: @last_order.id)

    # Current month orders
    @current_month_orders = Order.where('deliver_date >= ? and deliver_date <= ?', Time.now.beginning_of_month, Time.now.end_of_month)
    @current_eco_scores_table = []
    @current_nutri_scores_table = []
    @current_month_orders.each do |order|
      order.products.pluck(:eco_score).join.gsub("A", "6").gsub("B", "5").gsub("C", "4").gsub("D", "3").gsub("E", "2").gsub("F","1").split("").each { |grade| @current_eco_scores_table << grade.to_i}
      order.products.pluck(:nutri_score).join.gsub("A", "6").gsub("B", "5").gsub("C", "4").gsub("D", "3").gsub("E", "2").gsub("F","1").split("").each { |grade| @current_nutri_scores_table << grade.to_i}
    end
    @current_eco_score_avg = ((@current_eco_scores_table.inject { |sum, el| sum + el }.to_f) / @current_eco_scores_table.size).round(0)
      .to_s.gsub("6","A").gsub("5", "B").gsub("4", "C").gsub("3", "D").gsub("2", "E").gsub("1", "F")
    @current_nutri_score_avg = ((@current_nutri_scores_table.inject { |sum, el| sum + el }.to_f) / @current_nutri_scores_table.size).round(0)
    .to_s.gsub("6","A").gsub("5", "B").gsub("4", "C").gsub("3", "D").gsub("2", "E").gsub("1", "F")

    # Last month orders
    @last_month_orders = Order.where('deliver_date >= ? and deliver_date <= ?', Time.now.beginning_of_month - 1.month, Time.now.end_of_month - 1.month)
    @last_eco_scores_table = []
    @last_nutri_scores_table = []
    @last_month_orders.each do |order|
      order.products.pluck(:eco_score).join.gsub("A", "6").gsub("B", "5").gsub("C", "4").gsub("D", "3").gsub("E", "2").gsub("F","1").split("").each { |grade| @last_eco_scores_table << grade.to_i}
      order.products.pluck(:nutri_score).join.gsub("A", "6").gsub("B", "5").gsub("C", "4").gsub("D", "3").gsub("E", "2").gsub("F","1").split("").each { |grade| @last_nutri_scores_table << grade.to_i}
    end
    @last_eco_score_avg = ((@last_eco_scores_table.inject { |sum, el| sum + el }.to_f) / @last_eco_scores_table.size).round(0)
      .to_s.gsub("6","A").gsub("5", "B").gsub("4", "C").gsub("3", "D").gsub("2", "E").gsub("1", "F")
    @last_nutri_score_avg = ((@last_nutri_scores_table.inject { |sum, el| sum + el }.to_f) / @last_nutri_scores_table.size).round(0)
    .to_s.gsub("6","A").gsub("5", "B").gsub("4", "C").gsub("3", "D").gsub("2", "E").gsub("1", "F")
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/dashboards/overview.html.erb
<div class= "strange">
    <div class="rectangle-overview paper">
      <h2 class="overview-title text-left">
        Dashboard
      </h2>
      <div class="current-order">
        <h4 class="last-title mb-3">Last 5 Purchases</h4>
        <% Order.where(user_id: current_user.id).order("deliver_date desc").limit(5).each do |order|%>
          <ul>
            <li>
              <div class="list-dashboard">
                <div class="list-product-dashboard-infos">
                  <h5>Order n°<%=order.id %> - <%= order.products.count %> items ordered</h5>
                  <span><strong>Deliver Date:</strong> <%= order.deliver_date %> - <strong>Total:</strong> <%= order.total.round(2) %> CHF</span>
                  <br>
                  <%= link_to "Order details", order_path(order), class: "order-details" %>
                </div>
              </div>
            </li>
          </ul>
        <% end %>
      </div>
    </div>


    <div class="container charts-infos">
      <div class="row all-charts d-flex justify-content-between">

        <div class="eco-chart">
          <div class="eco-chart chart">
            <%= column_chart [
                    {
                        name: "A",

                        data: Product.joins(:orders).where("orders.user_id = ?", current_user.id).where("products.eco_score = 'A'").group('orders.id').count ,
                        stack: "stack 1",
                        color: ["#008000"],
                    },
                    {
                        name: "B",
                        data: Product.joins(:orders).where("orders.user_id = ?", current_user.id).where("products.eco_score = 'B'").group('orders.id').count ,
                        stack: "stack 1",
                        color: ["#00FF00"],
                    },
                    {
                        name: "C",
                        data: Product.joins(:orders).where("orders.user_id = ?", current_user.id).where("products.eco_score = 'C'").group('orders.id').count ,
                        stack: "stack 1",
                        color: ["#FFC300"],
                    },
                    {
                        name: "D",
                        data: Product.joins(:orders).where("orders.user_id = ?", current_user.id).where("products.eco_score = 'D'").group('orders.id').count ,
                        stack: "stack 1",
                        color: ["#FFC300"],
                    },
                    {
                        name: "E",
                        data: Product.joins(:orders).where("orders.user_id = ?", current_user.id).where("products.eco_score = 'E'").group('orders.id').count ,
                        stack: "stack 1",
                        color: ["#FF0000"],
                    },
                    {
                        name: "F",
                        data: Product.joins(:orders).where("orders.user_id = ?", current_user.id).where("products.eco_score = 'F'").group('orders.id').count ,
                        stack: "stack 1",
                        color: ["#800000"],
                    },
                ], stacked: true, legend: "left", title: "Eco Score"
            %>
          </div>
        </div>

        <div class="details-chart">
          <div class="nutritionnal-chart chart">
            <%= column_chart [
                    {
                        name: "A",
                        data: Product.joins(:orders).where("orders.user_id = ?", current_user.id).where("products.nutri_score = 'A'").group('orders.id').count ,
                        stack: "stack 1",
                        color: ["#008000"],
                    },
                    {
                        name: "B",
                        data: Product.joins(:orders).where("orders.user_id = ?", current_user.id).where("products.nutri_score = 'B'").group('orders.id').count ,
                        stack: "stack 1",
                        color: ["#00FF00"],

                    },
                    {
                        name: "C",
                        data: Product.joins(:orders).where("orders.user_id = ?", current_user.id).where("products.nutri_score = 'C'").group('orders.id').count ,
                        stack: "stack 1",
                        color: ["#FFC300"],
                    },
                    {
                        name: "D",
                        data: Product.joins(:orders).where("orders.user_id = ?", current_user.id).where("products.nutri_score = 'D'").group('orders.id').count ,
                        stack: "stack 1",
                        color: ["#FFC300"],
                    },
                    {
                        name: "E",
                        data: Product.joins(:orders).where("orders.user_id = ?", current_user.id).where("products.nutri_score = 'E'").group('orders.id').count ,
                        stack: "stack 1",
                        color: ["#FF0000"],
                    },
                    {
                        name: "F",
                        data: Product.joins(:orders).where("orders.user_id = ?", current_user.id).where("products.nutri_score = 'F'").group('orders.id').count ,
                        stack: "stack 1",
                        color: ["#800000"],
                    },
                ], stacked: true, legend: "left", title: "Nutri Score"
            %>
          </div>
        </div>

        <div class="spending-chart">
          <div class="spendings-chart chart">
            <%= column_chart Order.where(user_id: current_user.id).pluck(:id, :total), ytitle: "Total spent (CHF)", title: "Spendings" %>
          </div>
        </div>
      </div>



      <div class="row d-flex justify-content-between mt-5 top-buffer">
        <div class="col-5">
          <h4 class="d-flex align-items-start">Last Month Overview</h4>
          <ul>
            <li><p>Global Ecoscore: <strong><% if @last_eco_score_avg == "A" || @last_eco_score_avg == "B" %>
                                                  <i class="fas fa-globe-americas fa-1x" style="color: #4CA90C;"></i>
                                                <%elsif  @last_eco_score_avg == "C" || @last_eco_score_avg == "D" %>
                                                  <i class="fas fa-globe-americas fa-1x" style="color: #FFC400;"></i>
                                                <% else %>
                                                  <i class="fas fa-globe-americas fa-1x" style="color: #EB5757;"></i>
                                                <% end %></strong></p></li>
            <li><p>Global Nutriscore: <strong><% if @last_nutri_score_avg == "A" || @last_nutri_score_avg == "B" %>
                                                    <i class="fas fa-heartbeat fa-1x" style="color: #4CA90C;"></i>
                                                  <%elsif  @last_nutri_score_avg == "C" || @last_nutri_score_avg == "D" %>
                                                    <i class="fas fa-heartbeat fa-1x" style="color: #FFC400;"></i>
                                                  <% else %>
                                                    <i class="fas fa-heartbeat fa-1x" style="color: #EB5757;"></i>
                                                  <% end %></strong></p></li>
            <li><p>Total Spendings: <strong><%= @last_month_orders.pluck(:total).inject(0) {|sum, ele| sum += ele}.to_f.round(2) %> CHF</strong></p></li>
          </ul>
        </div>
        <div class="col-5">
          <h4 class="d-flex align-items-start">Current Month Overview</h4>
          <ul>
            <li><p>Global Ecoscore: <strong><% if @current_eco_score_avg == "A" || @current_eco_score_avg == "B" %>
                                                  <i class="fas fa-globe-americas fa-1x" style="color: #4CA90C;"></i>
                                                <%elsif  @current_eco_score_avg == "C" || @current_eco_score_avg == "D" %>
                                                  <i class="fas fa-globe-americas fa-1x" style="color: #FFC400;"></i>
                                                <% else %>
                                                  <i class="fas fa-globe-americas fa-1x" style="color: #EB5757;"></i>
                                                <% end %></strong></p></li>
            <li><p>Global Nutriscore: <strong><% if @current_nutri_score_avg == "A" || @current_nutri_score_avg == "B" %>
                                                    <i class="fas fa-heartbeat fa-1x" style="color: #4CA90C;"></i>
                                                  <%elsif  @current_nutri_score_avg == "C" || @current_nutri_score_avg == "D" %>
                                                    <i class="fas fa-heartbeat fa-1x" style="color: #FFC400;"></i>
                                                  <% else %>
                                                    <i class="fas fa-heartbeat fa-1x" style="color: #EB5757;"></i>
                                                  <% end %></strong></p></li>
            <li><p>Total Spendings: <strong><%= @current_month_orders.pluck(:total).inject(0) {|sum, ele| sum += ele}.to_f.round(2) %> CHF</strong></p></li>
          </ul>
        </div>
      </div>
    </div>
  </div>